apiVersion: batch/v1
kind: Job
metadata:
  name: panet-inference
spec:
  parallelism: 32
  template:
    metadata:
      name: job-panet-inference
    spec:
      containers:
      - name: inference
        image: jtrneo/panet:inferjsonv1
        volumeMounts:
                    - name: nfs
                      mountPath: "/mnt"
        resources:
                    limits:
                      nvidia.com/gpu: 1

      restartPolicy: OnFailure
      volumes:
               - name: nfs
                 nfs:
                   path: /raid/jsdata
                   server: 172.31.20.20
#      nodeSelector:
#          distype: dg1
