apiVersion: batch/v1
kind: Job
metadata:
  name: sniper-inference
spec:
  parallelism: 32
  template:
    metadata:
      name: job-sniper-inference
    spec:
      containers:
      - name: inference
        image: jtrneo/sniper:inferk8s
        volumeMounts:
                    - name: nfs
                      mountPath: "/mnt"
        resources:
                    limits:
                      nvidia.com/gpu: 1
        command: ['sh','demo_mask_satellite_local.sh']
      restartPolicy: OnFailure
      volumes:
               - name: nfs
                 nfs:
                   path: /raid/jsdata
                   server: 172.31.20.20
#      nodeSelector: 
#           distype: dg1

